// Chrono Trigger camp-fire scene on the TI-89 / Titanium, 4 grey levels.
// The map (trees, ground, glow) is a TileMap plane; the fire is an 8-frame animation drawn over
// it; the 7 characters are masked sprites with a white outline. Arrows scroll the 256x224 scene,
// 2nd = faster, ESC quits. Data: data.h, generated by tools/extract.py from the GIF, packed by
// tools/pack.py into zdata.h (tiles, sprites and fire as one ZX0 stream, unpacked at start-up by
// the asm decoder zx0_asm).
// Build: ti-cc -o campfire campfire.c ../../lib/unpack68k.s ../../tools/extgraph/lib/tilemap.a
#define USE_TI89
#define SAVE_SCREEN
#include <tigcclib.h>
#include "extgraph.h"
#include "tilemap.h"
#include "../../lib/unpack68k.h"
#include "zdata.h"

typedef struct { short x, y, h; const unsigned long *l, *d, *m; } SPR;
static SPR sprites[NSPR];                       // point into the unpacked data
static const unsigned long (*fire_l)[FIRE_H], (*fire_d)[FIRE_H];

#define VIEW_W 160
#define VIEW_H 100
#define FRAME_TICKS 8          // 256 Hz / 8 = 32 fps
#define FIRE_TICKS 51          // 200 ms per fire frame, as in the GIF

static volatile unsigned short ticks;
DEFINE_INT_HANDLER(tick_handler) { ticks++; }

static void draw_scene(short cx, short cy, Plane *pl)
{
    void *light = GrayDBufGetHiddenPlane(LIGHT_PLANE), *dark = GrayDBufGetHiddenPlane(DARK_PLANE);
    const SPR *s;
    unsigned char f = fire_seq[(unsigned short)(ticks / FIRE_TICKS) % NFSEQ];
    short k;

    // dark plane first: GrayDBuf keeps it 3840 bytes before the light one (tile rows interlaced so)
    DrawPlane(cx, cy, pl, dark, TM_GRPLC89, TM_G16B);
    GrayClipSprite32_RPLC_R(FIRE_X - cx, FIRE_Y - cy, FIRE_H, fire_l[f], fire_d[f], light, dark);
    for (k = 0, s = sprites; k < NSPR; k++, s++)
        GrayClipSprite32_MASK_R(s->x - cx, s->y - cy, s->h, s->l, s->d, s->m, s->m, light, dark);
}

void _main(void)
{
    INT_HANDLER old_int1 = GetIntVec(AUTO_INT_1);
    void *dbuf = malloc(GRAYDBUFFER_SIZE);
    char *big = malloc(GRAY_BIG_VSCREEN_SIZE);
    unsigned char *raw = malloc(RAW_LEN);
    Plane pl;
    short cx = (SCENE_W - VIEW_W) / 2, cy = (SCENE_H - VIEW_H) / 2;   // start centred on the fire
    unsigned short last;

    short k;

    if (!dbuf || !big || !raw) goto out;
    zx0_asm(zdata, raw);                           // tiles at 0, sprites, then the fire frames
    for (k = 0; k < NSPR; k++) {
        const SPRZ *z = &sprz[k];
        SPR *s = &sprites[k];
        s->x = z->x; s->y = z->y; s->h = z->h;
        s->l = (const unsigned long *)(raw + z->ofs); s->d = s->l + z->h; s->m = s->d + z->h;
    }
    fire_l = (const unsigned long (*)[FIRE_H])(raw + FIRE_OFF);
    fire_d = fire_l + NFIRE;
    pl.matrix = map; pl.width = MAP_W; pl.sprites = raw; pl.big_vscreen = big;
    pl.force_update = 1;

    SetIntVec(AUTO_INT_1, DUMMY_HANDLER);          // before GrayOn (KB rule)
    if (!GrayOn()) goto out;
    GraySetInt1Handler(tick_handler);
    GrayDBufInit(dbuf);

    last = ticks;
    while (!_keytest(RR_ESC)) {
        short step = _keytest(RR_2ND) ? 4 : 2;
        if (_keytest(RR_LEFT))  cx -= step;
        if (_keytest(RR_RIGHT)) cx += step;
        if (_keytest(RR_UP))    cy -= step;
        if (_keytest(RR_DOWN))  cy += step;
        if (cx < 0) cx = 0; else if (cx > SCENE_W - VIEW_W) cx = SCENE_W - VIEW_W;
        if (cy < 0) cy = 0; else if (cy > SCENE_H - VIEW_H) cy = SCENE_H - VIEW_H;

        draw_scene(cx, cy, &pl);
        GrayDBufToggleSync();                      // swap at a plane switch: no tearing
        while ((unsigned short)(ticks - last) < FRAME_TICKS) pokeIO(0x600005, 0x1D);   // sleep
        last += FRAME_TICKS;
        if ((unsigned short)(ticks - last) > 2 * FRAME_TICKS) last = ticks;   // too slow: no catch-up
    }
    while (_keytest(RR_ESC)) ;                     // do not leak ESC to AMS

    GraySetInt1Handler(DUMMY_HANDLER);
    GrayOff();
out:
    SetIntVec(AUTO_INT_1, old_int1);
    free(raw);
    free(big);
    free(dbuf);
    GKeyFlush();
}
