#!/usr/bin/env python3
"""Our own art for the FFT tech demo (no disc data) -> art.h (committed).

usage: art.py art.h
Greys: 0 white, 1 light, 2 dark, 3 black (light plane = bit 0, dark plane = bit 1).
The scenery is the game's own (tools/extract.py: the map's textured mesh drawn per view);
and so are the units (tools/units.py -> units.h); this file holds the rest:
- The units' shadow (ExtGraph sprite rows, mask bit 1 = transparent) and rev8, a byte with
  its bits reversed (the units' sprites mirrored, as FFT draws two of the four directions).
- The cursor and the reach marker (24x12 diamonds); the arrow above enemies (team at a glance).
- The 4 solid greys of the rotation frames (8x8 polygon patterns); each face's grey comes from
  the views (extract.py, map.h).
"""
import sys


def diamond_rows():
    """Column span of each of the 12 rows of the 24x12 diamond (tiles with neighbours at
    (+-12, +-6) exactly)."""
    out = []
    for r in range(12):
        k = r if r < 6 else 11 - r
        out.append((10 - 2 * k, 14 + 2 * k))   # [x0, x1)
    return out


def plane_rows(pix, w, h, x0=0):
    """pix[y][x] grey or None -> light, dark, mask as u32 rows (bit 31 = column x0)."""
    L, D, M = [], [], []
    for y in range(h):
        l = d = m = 0
        for x in range(w):
            v = pix[y][x]
            if v is None:
                continue
            bit = 1 << (31 - x - x0)
            m |= bit
            if v & 1:
                l |= bit
            if v & 2:
                d |= bit
        L.append(l); D.append(d); M.append(m)
    return L, D, M


def overlay_hi():
    """The reach marker on a 24x12 tile: a solid black line inset 3 px along the edges, a white
    one outside it (inset 1-2 px), readable on light and dark floors alike (chosen among four:
    the first dotted black line, the same solid, this one, dotted with a lightened inside)."""
    rows = diamond_rows()
    pix = [[None] * 24 for _ in range(12)]
    for y, (x0, x1) in enumerate(rows):
        if not 2 <= y <= 9:
            continue
        for x in (x0 + 3, x0 + 4, x1 - 5, x1 - 4):
            if x0 + 3 < x1 - 4:
                pix[y][x] = 3
        for x in (x0 + 1, x0 + 2, x1 - 3, x1 - 2):
            if pix[y][x] is None:
                pix[y][x] = 0
    for y in (1, 10):                   # the white line's top and bottom rows
        x0, x1 = rows[y]
        for x in range(x0 + 1, x1 - 1):
            pix[y][x] = 0
    return pix


def cursor():
    rows = diamond_rows()
    pix = [[None] * 24 for _ in range(12)]
    for y, (x0, x1) in enumerate(rows):
        for x in (x0, x0 + 1, x1 - 2, x1 - 1):
            pix[y][x] = 3 if x in (x0, x1 - 1) else 0
    return pix


FOE = """
....000000000...
....033333330...
.....0333330....
......03330.....
.......030......
........0.......
"""                                     # above an enemy's head: a black arrow, white border

SHADOW = """
....222222222.
...22222222222
....222222222.
"""                                     # 16 wide, the units' anchor at column 8

# 8x8 polygon patterns (the rotation frames): rows of (light, dark) bytes,
# written doubled as 16-bit words
def pattern(f):
    L, D = [], []
    for y in range(8):
        l = d = 0
        for x in range(8):
            v = f(x, y)
            if v & 1: l |= 0x80 >> x
            if v & 2: d |= 0x80 >> x
        L.append(l); D.append(d)
    return L, D


def main():
    out = open(sys.argv[1], 'w')
    w = out.write
    w('// Generated by tools/art.py (our own art, committed). See that file for the layout.\n')

    def arr(name, rows, fmt='0x%08lXUL'):
        w('static const u32 %s[%d] = { %s };\n' % (name, len(rows), ', '.join(fmt % r for r in rows)))

    L, D, M = plane_rows(overlay_hi(), 24, 12)
    arr('hi_l', L); arr('hi_d', D); arr('hi_m', M)
    L, D, M = plane_rows(cursor(), 24, 12)
    arr('cur_l', L); arr('cur_d', D); arr('cur_m', M)
    sh = [[None if c == '.' else int(c) for c in l] for l in SHADOW.strip('\n').split('\n')]
    sh = [r + [None] * (16 - len(r)) for r in sh]
    L, D, M = plane_rows(sh, 16, len(sh))
    w('static const u8 rev8[256] = { %s };\n' % ', '.join(str(int('{:08b}'.format(i)[::-1], 2)) for i in range(256)))
    w('static const u16 shadow_gfx[3][%d] = { { %s }, { %s }, { %s } };\n' % (len(sh), *(', '.join('0x%04lX' % (v >> 16) for v in P) for P in (L, D, [~m & 0xFFFF0000 for m in M]))))
    # rotation frames (half resolution): solid greys (checkerboards between two greys were
    # tried: the user preferred solid faces)
    foe = [[None if c == '.' else int(c) for c in l] for l in FOE.strip('\n').split('\n')]
    L, D, M = plane_rows(foe, 16, len(foe))
    w('#define FOE_H %d\n' % len(foe))
    w('static const u16 foe_gfx[3][FOE_H] = { { %s }, { %s }, { %s } };\n' % tuple(', '.join('0x%04lX' % (v >> 16) for v in P) for P in (L, D, [~m & 0xFFFF0000 for m in M])))
    w('#define SHADES 4\n')
    w('static const u16 turn_pat[SHADES][2][8] = {\n')
    for k in range(4):
        L, D = pattern(lambda x, y: k)
        w('    { { %s }, { %s } },\n' % (', '.join('0x%04X' % (v << 8 | v) for v in L), ', '.join('0x%04X' % (v << 8 | v) for v in D)))
    w('};\n')
    out.close()


if __name__ == '__main__':
    main()
