#!/usr/bin/env python3
"""FFA sprites: ASCII art -> gfx.h (ExtGraph layout: light, dark, mask; mask bit 1 = transparent).
Art chars: '.' transparent, 'w' white, 'l' light grey, 'd' dark grey, 'b' black.
Main sprites get a 1-pixel white outline (shape dilated in 8 directions) for visibility.
Run: python3 tools/gfx.py > gfx.h   (from games/ffa)"""

LEVEL = {'w': 0, 'l': 1, 'd': 2, 'b': 3}

HERO_DOWN = [                    # 14x22 art in a 16x24 sprite (outline added)
    "....bbbbbb....",
    "...bddddddb...",
    "..bddddddddb..",
    ".bdddlddlddddb",
    ".bddlllllldddb",
    ".bdlwwllwwldb.",
    ".bdlbwllwbldb.",
    "..blllllllb...",
    "...bllllbbb...",
    "..bbbdddbbb...",
    ".bwwbddddbwwb.",
    "bwwlbdwwdblwwb",
    "bwlbddwwddblwb",
    "blbbdddddddbbl",
    "bllbddddddbllb",
    ".bbbbbbbbbbbb.",
    "..bdddbbdddb..",
    "..bddb..bddb..",
    "..bllb..bllb..",
    "..bddb..bddb..",
    ".bbbbb..bbbbb.",
    ".bdddb..bdddb.",
]


def grid(rows, w, h, ox=0, oy=0):
    g = [[None] * w for _ in range(h)]
    for y, r in enumerate(rows):
        for x, c in enumerate(r):
            if c != '.':
                g[oy + y][ox + x] = LEVEL[c]
    return g


def outlined(g, level=0):
    h, w = len(g), len(g[0])
    out = [r[:] for r in g]
    for y in range(h):
        for x in range(w):
            if g[y][x] is None and any(0 <= y + j < h and 0 <= x + i < w and g[y + j][x + i] is not None
                                       for j in (-1, 0, 1) for i in (-1, 0, 1)):
                out[y][x] = level
    return out


def mirror(g):
    return [r[::-1] for r in g]


def planes(g, width):
    light, dark, mask = [], [], []
    for r in g:
        l = d = m = 0
        for x in range(width):
            v = r[x] if x < len(r) else None
            bit = 1 << (width - 1 - x)
            if v is None:
                m |= bit
            else:
                l |= bit if v & 1 else 0
                d |= bit if v & 2 else 0
        light.append(l); dark.append(d); mask.append(m)
    return light, dark, mask


def emit(name, sprites, width, h, ctype, out):
    fmt = '0x%0' + str(width // 4) + 'X'
    for k, part in enumerate(('light', 'dark', 'mask')):
        out.append(f"static const {ctype} {name}_{part}[{len(sprites)}][{h}] = {{")
        for s in sprites:
            out.append("    { " + ", ".join(fmt % v for v in s[k]) + " },")
        out.append("};")


def main():
    out = ["// Generated by tools/gfx.py: do not edit. ExtGraph sprite rows: light, dark, mask (1 = transparent)."]
    hero = [outlined(grid(HERO_DOWN, 16, 24, 1, 1))]
    emit("hero", [planes(g, 16) for g in hero], 16, 24, "u16", out)
    print("\n".join(out))


main()
