#!/usr/bin/env python3
"""FFA rooms -> rooms.h (collision grid, doors, triggers, tile map, per-room tile set).

One original 9-px cell = one 16x16 tile. Logic grid = murparse.Room.grid, padded with walls to
at least 11 x 7 cells (the TileMap engine's screen) and centred: pad offsets are applied to the
arrival cells. Cell codes (u8): 0 wall, 1 floor, 0x80|d door d (solid, bumping opens it),
0x40|t trigger t (value in the room's trigger table, original p x 10: <= -20 text (solid, read
with 2nd), >= 5000 story script (walkable, runs when stepped on)).

Tiles: art from ART (tools/art.py) when the room has a layout, else the original picture
upscaled 9 -> 16 px (nearest), deduplicated: the 8-bit stand-in used while the engine is built.

Run: tools/pyenv/bin/python tools/rooms.py > rooms.h   (from games/ffa)
"""
import os
import sys
from fractions import Fraction
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from murparse import Room
import art

HERE = os.path.dirname(os.path.abspath(__file__))
PICS = os.path.join(HERE, '..', '..', '..', 'ffa_en', 'pictures')
PART1 = [8, 6, 5, 4, 7, 18, 10, 11, 12, 13, 14, 15, 16, 17]   # castle, then the dungeon
FRONTIER = {19: 'world'}                                     # doors leading out of part I
MIN_W, MIN_H = 11, 7
KEY_NEVER = 0xFD                    # key flag that no original program ever sets: always locked


def settable_flags():
    import re
    txt = open(os.path.join(HERE, '..', '..', '..', 'ffa_en', 'ffa_decoded.txt'), encoding='utf-8').read()
    return {int(k) for k in re.findall(r'\u2192clef\[(\d+),1\]', txt)}


def cell_code(v, room, trig):
    if v == 0:
        return 0
    if 2 < v < 500:
        d = room.door_index(int(v))
        if d is None:
            return 0
        return 0x80 | d
    if v >= 500 or v <= -2:
        t = int(v * 10)
        if t not in trig:
            trig.append(t)
        return 0x40 | trig.index(t)
    return 1 if v > Fraction(9, 10) else 0


def picture_tiles(u, w, h, px, py):
    """Stand-in tiles: the original picture, one 9x9 cell -> 16x16, at grid (a/9 + 1, b/9 + 1)."""
    path = os.path.join(PICS, 'dec%d.png' % u)
    src = Image.open(path).convert('L') if os.path.exists(path) else Image.new('L', (153, 71), 0)
    big = Image.new('L', (w * 16, h * 16), 0)             # outside the picture: black
    up = src.resize((src.width * 16 // 9, src.height * 16 // 9), Image.NEAREST)
    big.paste(up, ((1 + px) * 16, (1 + py) * 16))
    tiles, tmap = [], []
    for ty in range(h):
        for tx in range(w):
            t = big.crop((tx * 16, ty * 16, tx * 16 + 16, ty * 16 + 16))
            rows = []
            for y in range(16):
                d = l = 0
                for x in range(16):
                    if t.getpixel((x, y)) < 128:     # black pixels of the 1-bit art
                        d |= 0x8000 >> x
                        l |= 0x8000 >> x
                rows.append((d, l))
            key = tuple(rows)
            if key not in tiles:
                tiles.append(key)
            tmap.append(tiles.index(key))
    return tiles, tmap


def build(u):
    r = Room(u)
    w, h = max(r.w, MIN_W), max(r.h, MIN_H)
    px, py = (w - r.w) // 2, (h - r.h) // 2
    trig, cells = [], [0] * (w * h)
    for y in range(r.h):
        for x in range(r.w):
            cells[(y + py) * w + x + px] = cell_code(r.grid[y][x], r, trig)
    doors = []
    for d in r.doors:
        doors.append(d)
    if u in art.LAYOUTS:
        lay = art.LAYOUTS[u]
        v = art.View(r, lay)
        g = art.render_layout(v, lay)
        big = [[3] * (w * 16) for _ in range(h * 16)]      # padding: black
        for y in range(len(g)):
            for x in range(len(g[0])):
                big[py * 16 + y][px * 16 + x] = g[y][x]
        tiles, tmap = art.tiles_of(big, w, h)
    else:
        tiles, tmap = picture_tiles(u, w, h, px, py)
    return {'u': u, 'w': w, 'h': h, 'px': px, 'py': py, 'frc': int(r.frc * 10), 'cells': cells,
            'trig': trig, 'doors': doors, 'tiles': tiles, 'tmap': tmap}


def main():
    settable = settable_flags()
    rooms = [build(u) for u in PART1]
    idx = {rm['u']: k for k, rm in enumerate(rooms)}
    out = ['// Generated by tools/rooms.py from the original FFA matrices: do not edit.',
           '#define NROOM %d' % len(rooms), '']
    for rm in rooms:
        u = rm['u']
        out.append('static const u8 r%d_cell[%d] = {' % (u, len(rm['cells'])))
        for y in range(rm['h']):
            out.append('    ' + ','.join('%d' % c for c in rm['cells'][y * rm['w']:(y + 1) * rm['w']]) + ',')
        out.append('};')
        out.append('static const u8 r%d_map[%d] = {' % (u, len(rm['tmap'])))
        for y in range(rm['h']):
            out.append('    ' + ','.join('%d' % c for c in rm['tmap'][y * rm['w']:(y + 1) * rm['w']]) + ',')
        out.append('};')
        out.append('static const u16 r%d_tiles[%d] = {' % (u, 32 * len(rm['tiles'])))
        for t in rm['tiles']:
            out.append('    ' + ','.join('0x%04X,0x%04X' % p for p in t) + ',')
        out.append('};')
        out.append('static const s16 r%d_trig[%d] = { %s };' % (u, max(1, len(rm['trig'])),
                                                              ', '.join(map(str, rm['trig'])) or '0'))
        ds = []
        for d in rm['doors']:
            tgt = d['room']
            if tgt in idx:
                dest = idx[tgt]
            elif tgt in FRONTIER:
                dest = 0xFE                                   # leaves part I
            else:
                dest = 0xFF                                   # out of scope: never opens
            tr = rooms[idx[tgt]] if tgt in idx else None
            ax = d['a'] // 9 + 1 + tr['px'] if tr and d['a'] >= 0 else -1
            ay = d['b'] // 9 + 1 + tr['py'] if tr and d['b'] >= 0 else -1
            key = d['key']
            if key > 0 and key not in settable:
                key = KEY_NEVER
            ds.append('{ %d, %d, %d, %d }' % (dest, max(key, -1) & 0xFF, ax, ay))
        out.append('static const Door r%d_door[%d] = { %s };' % (u, max(1, len(ds)), ', '.join(ds) or '{ 0 }'))
        out.append('')
    out.append('const Room rooms[NROOM] = {')
    for rm in rooms:
        u = rm['u']
        out.append('    { %d, %d, %d, %d, %d, %d, %d, %d, r%d_cell, r%d_trig, r%d_door, { r%d_map, %d, %d, r%d_tiles, %d } },'
                   % (u, rm['w'], rm['h'], rm['px'], rm['py'], rm['frc'], len(rm['doors']), len(rm['trig']),
                      u, u, u, u, rm['w'], rm['h'], u, len(rm['tiles'])))
    out.append('};')
    out.append('const u8 room_index[%d] = { %s };' % (
        max(idx) + 1, ', '.join(str(idx.get(k, 255)) for k in range(max(idx) + 1))))
    out.append("const u8 nroom = NROOM;")
    print("\n".join(out))
    for rm in rooms:
        print('room %2d: %2dx%-2d pad %d,%d tiles %3d triggers %s doors %s' % (
            rm['u'], rm['w'], rm['h'], rm['px'], rm['py'], len(rm['tiles']), rm['trig'],
            [d['room'] for d in rm['doors']]), file=sys.stderr)


if __name__ == '__main__':
    main()
