# Runtime self-tests: make test (PC, headless), make ti (xcheck.89z for the calculator),
# make pc (xcheck in a window). Mono variant: make CFLAGS_GAME=-DRT_MONO NAME=xcheckm ...
NAME ?= xcheck
SRC := xcheck.c
TESTS := test_runtime.c
include ../rt.mk
