#!/usr/bin/env python3
"""Build-time data for the Celeste port, from the extracted cart (p8extract.py output):
  room.h  the logic data: room 0's 16x16 tile numbers and the 256 sprite flags (exact)
  gfx.h   the graphics: room 0 as 8x8 cell pictures (the map's bg and terrain layers over the
          background colour), the player (7 frames x 2 hair states x 2 facings), the fruit, the
          fake wall, the smoke, all converted from the cart's sheet to 4 greys
usage: gfx.py CART_X_DIR OUT_DIR [STYLE]   STYLE: A dark (the original's look), B light with
       black terrain (default), C light with dark grey terrain. Every style keeps the contrast
       high (decision Q9): black and white first, greys sparingly, the player outlined in white."""
import sys

X, OUT = sys.argv[1], sys.argv[2]
STYLE = sys.argv[3] if len(sys.argv) > 3 else 'B'
mp = open(X + '/map.bin', 'rb').read()
fl = open(X + '/flags.bin', 'rb').read()
sheet = open(X + '/sprites.bin', 'rb').read()
ROOM = [mp[y * 128 + x] for y in range(16) for x in range(16)]   # room (0, 0)

# PICO-8 colour -> grey (0 white, 1 light, 2 dark, 3 black) per group of graphics. The cart's
# colours: 0 black (transparent in sprites), 1 dark blue, 3 dark green, 5 dark grey, 6 light
# grey, 7 white, 8 red (hair), 11 green, 12 blue, 13 lavender, 14 pink, 15 peach (skin).
STYLES = {
    # background, terrain, bg layer (rocks, plants), player body, hair (1 dash, 0 dash), smoke
    'A': dict(bg=3, terrain={7: 0, 12: 1, 6: 1, 13: 1, 1: 2, 5: 2},
              back={5: 2, 1: 2, 13: 2, 6: 1, 7: 1, 3: 2, 11: 1, 14: 1, 8: 1, 12: 2},
              body={15: 0, 1: 3, 3: 2, 7: 0}, hair=(2, 0), smoke=0, fruit={8: 0, 2: 1, 9: 3, 3: 1, 11: 0}),
    'B': dict(bg=0, terrain={7: 3, 12: 3, 6: 2, 13: 2, 1: 3, 5: 2},
              back={5: 1, 1: 1, 13: 1, 6: 1, 7: 1, 3: 2, 11: 2, 14: 2, 8: 2, 12: 1},
              body={15: 0, 1: 3, 3: 3, 7: 3}, hair=(3, 1), smoke=2, fruit={8: 3, 2: 3, 9: 0, 3: 2, 11: 2}),
    'C': dict(bg=0, terrain={7: 3, 12: 2, 6: 2, 13: 2, 1: 3, 5: 3},
              back={5: 1, 1: 1, 13: 1, 6: 1, 7: 1, 3: 1, 11: 1, 14: 1, 8: 1, 12: 1},
              body={15: 0, 1: 3, 3: 3, 7: 3}, hair=(3, 1), smoke=2, fruit={8: 3, 2: 3, 9: 0, 3: 2, 11: 2}),
}
ST = STYLES[STYLE]


def carray(name, ctype, vals, per=16):
    s = 'static const %s %s[%d] = {\n' % (ctype, name, len(vals))
    for i in range(0, len(vals), per):
        s += '    ' + ', '.join(str(v) for v in vals[i:i + per]) + ',\n'
    return s + '};\n'


def pix(n, x, y):                                   # colour of pixel (x, y) of sprite n
    return sheet[(n // 16 * 8 + y) * 128 + n % 16 * 8 + x]


with open(OUT + '/room.h', 'w') as f:
    f.write('// generated by gfx.py from the cart: room 0 tiles, sprite flags\n')
    f.write(carray('room_tiles', 'u8', ROOM))
    f.write(carray('tile_flags', 'u8', list(fl)))

# ---------------------------------------------------------------- the room, as 8x8 cells
# The cart draws map(..., 4) (bg layer) then map(..., 2) (terrain); no cell is in both, tile 0
# and the object tiles (spawn 1, fake wall 64) are not map tiles: background only.
def cell_picture(t):
    g = [[ST['bg']] * 8 for _ in range(8)]
    group = ST['terrain'] if fl[t] & 2 else ST['back'] if fl[t] & 4 else None
    if t and group is not None:
        for y in range(8):
            for x in range(8):
                c = pix(t, x, y)
                if c:
                    g[y][x] = group.get(c, 3)
    return g


cells, cell_map = [], []
for t in ROOM:
    g = cell_picture(t)
    if g not in cells:
        cells.append(g)
    cell_map.append(cells.index(g))
cell_l, cell_d = [], []
for g in cells:
    for r in g:
        cell_l.append(sum(0x80 >> x for x, v in enumerate(r) if v & 1))
        cell_d.append(sum(0x80 >> x for x, v in enumerate(r) if v & 2))


# ---------------------------------------------------------------- sprites
def outlined(g):                                    # white ring around the opaque pixels
    h, w = len(g), len(g[0])
    o = [r[:] for r in g]
    for y in range(h):
        for x in range(w):
            if g[y][x] is None and any(0 <= y + dy < h and 0 <= x + dx < w and g[y + dy][x + dx] is not None
                                       for dy in (-1, 0, 1) for dx in (-1, 0, 1)):
                o[y][x] = 0
    return o


def from_sheet(ns, cols, mapping, flip=False, pad=0):
    """grey grid (None = transparent) of sprites ns (row-major, cols wide), padded by pad px"""
    rows = len(ns) // cols
    w, h = cols * 8, rows * 8
    g = [[None] * (w + 2 * pad) for _ in range(h + 2 * pad)]
    for k, n in enumerate(ns):
        for y in range(8):
            for x in range(8):
                c = pix(n, x, y)
                if c:
                    gx = (k % cols) * 8 + x
                    if flip: gx = w - 1 - gx
                    g[pad + (k // cols) * 8 + y][pad + gx] = mapping.get(c, 3)
    return g


def sprite_arrays(name, g, width):
    t = {8: 'u8', 16: 'u16', 32: 'u32'}[width]
    light, dark, mask = [], [], []
    for r in g:
        r = r + [None] * (width - len(r))
        light.append(sum((1 << (width - 1 - x)) for x, v in enumerate(r) if v is not None and v & 1))
        dark.append(sum((1 << (width - 1 - x)) for x, v in enumerate(r) if v is not None and v & 2))
        mask.append(sum((1 << (width - 1 - x)) for x, v in enumerate(r) if v is None))
    s = carray(name + '_l', t, light, 10) + carray(name + '_d', t, dark, 10) + carray(name + '_m', t, mask, 10)
    return s, '{ %d, %d, %s_l, %s_d, %s_m }' % (width, len(g), name, name, name)


out = ['// generated by gfx.py (style %s) from the cart\'s sheet\n' % STYLE,
       '#define GFX_NCELLS %d\n' % len(cells),
       carray('cell_l', 'u8', cell_l, 8), carray('cell_d', 'u8', cell_d, 8),
       carray('room_cells', 'u8', cell_map)]

# player: sprites 1..7, hair (colour 8) dark with 1 dash, light with 0 (decision Q9), both
# facings; 10x10 with the outline, drawn at (x - 1, y - 1), 16 wide for ExtGraph
inits = []
for hs in range(2):
    for flip in range(2):
        for n in range(1, 8):
            m = dict(ST['body']); m[8] = ST['hair'][hs]
            s, init = sprite_arrays('pl%d%d%d' % (hs, flip, n), outlined(from_sheet([n], 1, m, flip, 1)), 16)
            out.append(s); inits.append(init)
groups = ['{ %s }' % ', '.join('{ %s }' % ', '.join(inits[(h * 2 + f) * 7:(h * 2 + f + 1) * 7])
                                for f in range(2)) for h in range(2)]
out.append('static const RtSprite spr_player[2][2][7] = {  // [1 dash ? 0 : 1][flip][spr - 1]\n    %s\n};\n'
           % ',\n    '.join(groups))
s, init = sprite_arrays('fruit', outlined(from_sheet([26], 1, ST['fruit'], pad=1)), 16)
out += [s, 'static const RtSprite spr_fruit = %s;\n' % init]
s, init = sprite_arrays('fwall', from_sheet([64, 65, 80, 81], 2, ST['terrain']), 16)
out += [s, 'static const RtSprite spr_fakewall = %s;\n' % init]
inits = []
for n in (29, 30, 31):
    s, init = sprite_arrays('smoke%d' % n, from_sheet([n], 1, {7: ST['smoke']}), 8)
    out.append(s); inits.append(init)
out.append('static const RtSprite spr_smoke[3] = {\n    %s\n};\n' % ',\n    '.join(inits))
out.append('#define GFX_HAIR_1 %d\n#define GFX_HAIR_0 %d\n#define GFX_BG %d\n' % (ST['hair'][0], ST['hair'][1], ST['bg']))
open(OUT + '/gfx.h', 'w').write(''.join(out))
print('gfx.py: style %s, %d cell pictures' % (STYLE, len(cells)), file=sys.stderr)
