#!/usr/bin/env python3
"""Generate integer full-LCD projection and bold score glyphs offline."""
from pathlib import Path

DEST = Path(__file__).resolve().parents[1] / "generated" / "layout.h"


def table(kind, name, values):
    rows = [", ".join(map(str, values[i:i + 16])) for i in range(0, len(values), 16)]
    return "static const " + kind + " " + name + "[] = {\n    " + ",\n    ".join(rows) + "\n};\n"


def number_pixels():
    # Compact six-pixel figures keep two-pixel strokes at 10 pixels high.
    segments = {
        "a": (1, 0, 4, 2), "b": (4, 1, 2, 4), "c": (4, 5, 2, 4),
        "d": (1, 8, 4, 2), "e": (0, 5, 2, 4), "f": (0, 1, 2, 4),
        "g": (1, 4, 4, 2),
    }
    digits = ["abcdef", "bc", "abdeg", "abcdg", "bcfg", "acdfg",
              "acdefg", "abc", "abcdefg", "abcdfg"]
    glyphs = []
    for active in digits:
        rows = [0] * 10
        for segment in active:
            x, y, width, height = segments[segment]
            for line in range(y, y + height):
                for column in range(x, x + width):
                    rows[line] |= 0x80 >> column
        glyphs.append(rows)
    return glyphs


def main():
    # ROM court X=16..304, Y=72..200; preserve logic coordinates unchanged.
    output = "/* Generated by tools/layout.py; native UI, no ROM data. */\n"
    output += table("s16", "court_x", [(x - 16) * 5 // 9 for x in range(321)])
    output += table("s8", "court_y", [(y - 72) * 25 // 32 for y in range(225)])
    glyphs = number_pixels()
    for name, inverse in (("score_pixels", False), ("digit_mask", True)):
        output += f"static const u8 {name}[10][10] = {{\n"
        for rows in glyphs:
            output += "    {" + ",".join(f"0x{(row ^ 255) if inverse else row:02x}" for row in rows) + "},\n"
        output += "};\n"
    DEST.parent.mkdir(exist_ok=True)
    DEST.write_text(output)


if __name__ == "__main__":
    main()
