// Draws the test room once with the game's own tile drawing (alundra.c built with -DBAKE, the
// PC software renderer: the same pixels as the TI) into its image, the background the game
// copies its view from: world.h (two planes, 1 bit per pixel, MSB left, 20 bytes x 100 rows,
// its row 0 at y = ROOM_Y; two bytes of padding: the view copy reads one word past a row).
// And its depth (alundra.h World): each pixel belongs to the last tile drawn over it (rows
// back to front; a tile's pixels: those it changes on a white screen or on a black one), a
// tile of row r hides the player when his row is above r: threshold 8 r (his y / 2 < 8 r).
// The village's image and depth are the game's own (tools/extract.py). From gfx.h: local.
//   usage: bake > world.h
#include <stdio.h>
#include <string.h>
#include "../../../runtime/platform-sw/rt_sw.h"
#include "../alundra.h"

void al_draw_world(s16 ox, s16 oy);
void al_draw_tile(u8 tx, u8 ty, s16 ox, s16 oy);

static int lit(int x, int y)            // the pixel's grey, 0 white .. 3 black
{
    const u8 *l = (const u8 *)rt_light, *d = (const u8 *)rt_dark;
    int o = y * RT_PBYTES + (x >> 3), b = 0x80 >> (x & 7);
    return (l[o] & b ? 1 : 0) | (d[o] & b ? 2 : 0);
}

static void print(const char *name, u8 img[2][100][20])
{
    int p, y, x;
    printf("static const u8 %s[2][20 * 100 + 2] = {\n", name);
    for (p = 0; p < 2; p++) {
        printf("  {");
        for (y = 0; y < 100; y++) {
            printf("\n    ");
            for (x = 0; x < 20; x++) printf("0x%02x,", img[p][y][x]);
        }
        printf("\n    0, 0 },\n");
    }
    printf("};\n");
}

int main(void)
{
    static u8 img[2][100][20], depth[2][100][20];
    static signed char own[100][160];
    int p, y, x, tx, ty;
    sw_init(0);
    al_world(W_TEST);
    draw_clear();
    al_draw_world(0, ROOM_Y);
    for (p = 0; p < 2; p++)
        for (y = 0; y < 100; y++)
            memcpy(img[p][y], (const u8 *)(p ? rt_dark : rt_light) + y * RT_PBYTES, 20);
    memset(own, -1, sizeof own);
    for (ty = 0; ty < world->h; ty++)
        for (tx = 0; tx < world->w; tx++)
            for (p = 0; p < 2; p++) {           // on white, then on black
                memset(rt_light, p ? 0xff : 0, RT_PBYTES * RT_H);
                memset(rt_dark, p ? 0xff : 0, RT_PBYTES * RT_H);
                al_draw_tile(tx, ty, 0, ROOM_Y);
                for (y = 0; y < 100; y++)
                    for (x = 0; x < 160; x++)
                        if (lit(x, y) != (p ? 3 : 0)) own[y][x] = ty;
            }
    for (y = 0; y < 100; y++)                   // per byte: its frontmost row, its pixels
        for (x = 0; x < 20; x++) {
            int k, t = -1, m = 0;
            for (k = 0; k < 8; k++)
                if (own[y][x * 8 + k] > t) t = own[y][x * 8 + k];
            for (k = 0; k < 8; k++)
                if (t > 0 && own[y][x * 8 + k] == t) m |= 0x80 >> k;
            depth[0][y][x] = t > 0 ? 8 * t : 0;
            depth[1][y][x] = m;
        }
    printf("// Generated by tools/bake.c from gfx.h: do not edit, do not commit.\n");
    printf("#define TEST_IWB 20\n#define TEST_IH 100\n");
    print("test_img", img);
    print("test_depth", depth);
    return 0;
}
