// Draws the test room once with the game's own tile drawing (alundra.c built with -DBAKE, the
// PC software renderer: the same pixels as the TI) into its image, the background the game
// copies its view from: world.h (two planes, 1 bit per pixel, MSB left, 20 bytes x 100 rows,
// its row 0 at y = ROOM_Y; two bytes of padding: the view copy reads one word past a row).
// The village's image is the game's own (tools/extract.py). Generated from gfx.h: local.
//   usage: bake > world.h
#include <stdio.h>
#include "../../../runtime/platform-sw/rt_sw.h"
#include "../alundra.h"

void al_draw_world(s16 ox, s16 oy);

int main(void)
{
    int p, y, x;
    sw_init(0);
    al_world(W_TEST);
    draw_clear();
    al_draw_world(0, ROOM_Y);
    printf("// Generated by tools/bake.c from gfx.h: do not edit, do not commit.\n");
    printf("#define TEST_IWB 20\n#define TEST_IH 100\n");
    printf("static const u8 test_img[2][20 * 100 + 2] = {\n");
    for (p = 0; p < 2; p++) {
        const u8 *pl = p ? (const u8 *)rt_dark : (const u8 *)rt_light;
        printf("  {");
        for (y = 0; y < 100; y++) {
            printf("\n    ");
            for (x = 0; x < 20; x++) printf("0x%02x,", pl[y * RT_PBYTES + x]);
        }
        printf("\n    0, 0 },\n");
    }
    printf("};\n");
    return 0;
}
