#!/usr/bin/env python3
"""ZX0 v2 packing on the PC, for zx0_asm (lib/unpack68k.s).

As a module:  sys.path.insert(0, 'lib'); import zx0pack; packed = zx0pack.pack(raw)
              c_array(name, packed) -> C source of 'static const unsigned char name[n] = {...};'
From a shell: python3 lib/zx0pack.py IN.bin OUT.h NAME
              -> OUT.h with NAME[] and #define NAME_RAW_LEN (the size of the unpack buffer)
Every stream is decoded back with dzx0 and compared before it is returned. Uses the host
compressor built from einar-saukas/ZX0: tools/bin/zx0 and tools/bin/dzx0 ($ZX0, $DZX0).
"""
import os
import subprocess
import sys
import tempfile

BIN = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tools', 'bin')
ZX0 = os.environ.get('ZX0', os.path.join(BIN, 'zx0'))
DZX0 = os.environ.get('DZX0', os.path.join(BIN, 'dzx0'))


def pack(raw):
    with tempfile.TemporaryDirectory() as t:
        open(os.path.join(t, 'in'), 'wb').write(raw)
        subprocess.run([ZX0, '-f', 'in', 'out'], check=True, capture_output=True, cwd=t)
        subprocess.run([DZX0, '-f', 'out', 'back'], check=True, capture_output=True, cwd=t)
        packed = open(os.path.join(t, 'out'), 'rb').read()
        if open(os.path.join(t, 'back'), 'rb').read() != raw:
            sys.exit('zx0pack: round trip failed')
    return packed


def c_array(name, data):
    rows = [','.join(str(b) for b in data[i:i + 32]) + ',' for i in range(0, len(data), 32)]
    return '\n'.join(['static const unsigned char %s[%d] = {' % (name, len(data))] + rows + ['};'])


if __name__ == '__main__':
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    raw = open(sys.argv[1], 'rb').read()
    packed = pack(raw)
    open(sys.argv[2], 'w').write('// Generated by lib/zx0pack.py from %s: do not edit.\n#define %s_RAW_LEN %d\n%s\n'
                                 % (os.path.basename(sys.argv[1]), sys.argv[3].upper(), len(raw), c_array(sys.argv[3], packed)))
    print('%s: %d B -> %d B (%d %%)' % (sys.argv[1], len(raw), len(packed), 100 * len(packed) // len(raw)))
