#!/usr/bin/env python3
"""data.h -> zdata.h: the tiles, character sprites and fire frames as one ZX0 v2 stream.

The raw blob is laid out as the 68000 sees it (big-endian): tiles, then each sprite's l, d, m
arrays in data.h order, then fire_l and fire_d. zdata.h keeps data.h's defines, map and fire_seq,
and adds the packed stream (unpacked at start-up by zx0_asm, lib/unpack68k.s), the raw length,
FIRE_OFF and a table of sprite offsets. Packing and round-trip check: lib/zx0pack.py.
Run after extract.py: python3 games/campfire/tools/pack.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'data.h')
DST = os.path.join(HERE, '..', 'zdata.h')
sys.path.insert(0, os.path.join(HERE, '..', '..', '..', 'lib'))
import zx0pack  # noqa: E402
ARRAY = re.compile(r'static const unsigned (short|long) (\w+)\[[^=]*=\s*\{(.*?)\};\n', re.S)

text = open(SRC).read()
raw, off = bytearray(), {}
for m in ARRAY.finditer(text):
    size = {'short': 2, 'long': 4}[m.group(1)]
    off[m.group(2)] = len(raw)
    for v in re.findall(r'0x[0-9A-Fa-f]+|\d+', re.sub(r'//[^\n]*', '', m.group(3))):
        raw += int(v, 0).to_bytes(size, 'big')
assert off['tiles'] == 0 and off['fire_d'] > off['fire_l']

spr = re.search(r'static const SPR sprites\[NSPR\] = \{(.*?)\};\n', text, re.S)
sprz = []
for x, y, h, l, d, mk in re.findall(r'\{(-?\d+),(-?\d+),(\d+),(\w+),(\w+),(\w+)\}', spr.group(1)):
    assert off[d] == off[l] + 4 * int(h) and off[mk] == off[d] + 4 * int(h)   # l, d, m consecutive
    sprz.append('{%s,%s,%s,%d}' % (x, y, h, off[l]))

packed = zx0pack.pack(bytes(raw))

rest = ARRAY.sub('', text)
rest = rest.replace(spr.group(0), '')
rest = re.sub(r'typedef struct \{[^}]*\} SPR;\n', '', rest)
out = ['// Generated by tools/pack.py from data.h: do not edit.', rest.rstrip('\n'),
       '#define RAW_LEN %d' % len(raw), '#define FIRE_OFF %d' % off['fire_l'],
       'typedef struct { short x, y, h; unsigned short ofs; } SPRZ;   // ofs (not off: a ROM-call macro): l, then d and m follow',
       'static const SPRZ sprz[NSPR] = {' + ','.join(sprz) + '};',
       zx0pack.c_array('zdata', packed)]
open(DST, 'w').write('\n'.join(out) + '\n')
print('raw %d B -> ZX0 %d B (%d %%)' % (len(raw), len(packed), 100 * len(packed) // len(raw)))
