// Generated by tools/gfx.py: do not edit. ExtGraph sprite rows: light, dark, mask (1 = transparent), in ffadat.
extern const u8 *gfx_data;                  // the sprite block of ffadat (world_load)
#define HERO_FRAMES 12
#define hero_light ((const u16 (*)[24])(gfx_data + 0))
#define hero_dark ((const u16 (*)[24])(gfx_data + 576))
#define hero_mask ((const u16 (*)[24])(gfx_data + 1152))
#define SPR_KING 0
#define SPR_OLEN 1
#define SPR_JESS 2
#define SPR_LARC 3
#define SPR_VILLAGER 4
#define SPR_SOLDIER 5
#define SPR_SELLER 6
#define SPR_PRISONER 7
#define chest_open_light ((const u16 (*)[16])(gfx_data + 1728))
#define chest_open_dark ((const u16 (*)[16])(gfx_data + 1760))
#define chest_open_mask ((const u16 (*)[16])(gfx_data + 1792))
#define NPC_KINDS 8
#define npc_light ((const u16 (*)[24])(gfx_data + 1824))
#define npc_dark ((const u16 (*)[24])(gfx_data + 4128))
#define npc_mask ((const u16 (*)[24])(gfx_data + 6432))
#define MON1_H 42
#define mon1_light ((const u32 (*)[42])(gfx_data + 8736))
#define mon1_dark ((const u32 (*)[42])(gfx_data + 8904))
#define mon1_mask ((const u32 (*)[42])(gfx_data + 9072))
#define MON2_H 61
#define mon2_light ((const u32 (*)[61])(gfx_data + 9240))
#define mon2_dark ((const u32 (*)[61])(gfx_data + 9484))
#define mon2_mask ((const u32 (*)[61])(gfx_data + 9728))
#define MON3_H 64
#define mon3_light ((const u32 (*)[64])(gfx_data + 9972))
#define mon3_dark ((const u32 (*)[64])(gfx_data + 10228))
#define mon3_mask ((const u32 (*)[64])(gfx_data + 10484))
#define BHERO_H 51
#define bhero_light ((const u32 (*)[51])(gfx_data + 10740))
#define bhero_dark ((const u32 (*)[51])(gfx_data + 11964))
#define bhero_mask ((const u32 (*)[51])(gfx_data + 13188))
#define bheror_light ((const u16 (*)[51])(gfx_data + 14412))
#define bheror_dark ((const u16 (*)[51])(gfx_data + 15024))
#define bheror_mask ((const u16 (*)[51])(gfx_data + 15636))
