// Generated by tools/gfx.py --ids: do not edit.
#define HERO_FRAMES 12
#define SPR_KING 0
#define SPR_OLEN 1
#define SPR_JESS 2
#define SPR_LARC 3
#define SPR_VILLAGER 4
#define SPR_SOLDIER 5
#define SPR_SELLER 6
#define SPR_PRISONER 7
#define NPC_KINDS 8
#define MON1_H 42
#define MON2_H 61
#define MON3_H 64
#define BHERO_H 42
#define BHEROS_H 42
