#!/usr/bin/env python3
"""Extract the AMS F_4x6 and F_6x8 fonts from the Titanium OS file into platform-sw/amsfont.h, so
PC builds draw text exactly as DrawStr does. Offsets found by searching the OS for the glyph
layouts (F_4x6: 6 bytes per char = advance + 5 rows; F_6x8: 8 rows), checked by eye.
Run: python3 runtime/tools/amsfont.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OS = os.path.join(HERE, '..', '..', 'tools', 'rom', 'TI89Titanium_OS.89u')
F4X6, F6X8 = 1023838, 764986
d = open(OS, 'rb').read()
out = ['// Generated by runtime/tools/amsfont.py from the TI-89 Titanium OS: do not edit.',
       '// F_4x6: advance, then 5 rows; F_6x8: 8 rows. MSB = leftmost pixel.']
for name, off, n in (('ams_f4x6', F4X6, 6 * 256), ('ams_f6x8', F6X8, 8 * 256)):
    b = d[off:off + n]
    out.append('static const unsigned char %s[%d] = {' % (name, n))
    out += [','.join('%d' % v for v in b[k:k + 32]) + ',' for k in range(0, n, 32)]
    out.append('};')
open(os.path.join(HERE, '..', 'platform-sw', 'amsfont.h'), 'w').write('\n'.join(out) + '\n')
